from fmp_data.alternative.mapping import (
    ALTERNATIVE_ENDPOINT_MAP,
    ALTERNATIVE_ENDPOINTS_SEMANTICS,
)
from fmp_data.company.mapping import COMPANY_ENDPOINT_MAP, COMPANY_ENDPOINTS_SEMANTICS
from fmp_data.economics.mapping import (
    ECONOMICS_ENDPOINT_MAP,
    ECONOMICS_ENDPOINTS_SEMANTICS,
)
from fmp_data.fundamental.mapping import (
    FUNDAMENTAL_ENDPOINT_MAP,
    FUNDAMENTAL_ENDPOINTS_SEMANTICS,
)
from fmp_data.institutional.mapping import (
    INSTITUTIONAL_ENDPOINT_MAP,
    INSTITUTIONAL_ENDPOINTS_SEMANTICS,
)

ALL_ENDPOINT_SEMANTICS = {
    **ALTERNATIVE_ENDPOINTS_SEMANTICS,
    **COMPANY_ENDPOINTS_SEMANTICS,
    **ECONOMICS_ENDPOINTS_SEMANTICS,
    **FUNDAMENTAL_ENDPOINTS_SEMANTICS,
    **INSTITUTIONAL_ENDPOINTS_SEMANTICS,
}

ALL_ENDPOINT_MAP = {
    **ALTERNATIVE_ENDPOINT_MAP,
    **COMPANY_ENDPOINT_MAP,
    **ECONOMICS_ENDPOINT_MAP,
    **FUNDAMENTAL_ENDPOINT_MAP,
    **INSTITUTIONAL_ENDPOINT_MAP,
}
