repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: "^README\\.md$"
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-json
      - id: detect-private-key
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        # Let ruff use pyproject.toml config instead of overriding here
        args: [ --fix, --exit-non-zero-on-fix ]
      # Add ruff formatter for consistent formatting
      - id: ruff-format

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.5
    hooks:
      - id: bandit
        args: [ "-c", "pyproject.toml" ]
        exclude: ^tests/

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: tests/.*

  # Local hooks
  - repo: local
    hooks:
    - id: pytest-check
      name: pytest-check
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
      stages: [pre-push]  # Only run on push, not on every commit
      args: [
          "--quiet",
          "--no-header",
          "--tb=short",
          "-v",
          "--disable-warnings",
      ]
