repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: "^README\\.md$"
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-json
      - id: detect-private-key
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        exclude: ^tests/

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: tests/.*

  # Local hooks using nox
  - repo: local
    hooks:
      # Core typecheck - runs on every commit (excludes optional features)
      - id: mypy-core
        name: "mypy: core package"
        entry: nox -s typecheck --no-install
        language: system
        files: ^fmp_data/.*\.py$
        pass_filenames: false
        require_serial: true

      # Optional: LangChain typecheck (manual only - slow)
      - id: mypy-langchain
        name: "mypy: langchain features"
        entry: nox -s typecheck_lang --no-install
        language: system
        pass_filenames: false
        always_run: true
        require_serial: true
        stages: [manual]  # Only run when explicitly called

      # Optional: MCP typecheck (manual only - slow)
      - id: mypy-mcp
        name: "mypy: mcp features"
        entry: nox -s typecheck_mcp --no-install
        language: system
        pass_filenames: false
        always_run: true
        require_serial: true
        stages: [manual]  # Only run when explicitly called

      # Comprehensive typecheck (manual only - very slow)
      - id: mypy-all
        name: "mypy: all features comprehensive"
        entry: nox -s typecheck_all --no-install
        language: system
        pass_filenames: false
        always_run: true
        require_serial: true
        stages: [manual]

      # Test runner on push
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
        args: [
            "--quiet",
            "--no-header",
            "--tb=short",
            "-v",
            "--disable-warnings",
        ]
