repos:
  # ───────── Core utility hooks ───────────────────────────────────────────
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: "^README\\.md$"
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-json
      - id: detect-private-key
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-docstring-first

  # ───────── Black code formatter ─────────────────────────────────────────
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3

  # ───────── Ruff (lint / fix) ─────────────────────────────────────────────
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # ───────── Bandit security scanner ──────────────────────────────────────
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.5
    hooks:
      - id: bandit
        name: bandit
        additional_dependencies: ["bandit[toml]"]
        args: ["-c", "pyproject.toml"]
        exclude: ^tests/

  # ───────── Secret scanning ──────────────────────────────────────────────
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: tests/.*

  # ───────── Local nox-powered helpers ────────────────────────────────────
  - repo: local
    hooks:
      - id: sync-groups
        name: Sync optional-deps → dependency-groups
        entry: python scripts/sync_groups.py
        language: system
        files: ^pyproject\.toml$
        pass_filenames: false

      - id: mypy-core
        name: "mypy: core package"
        entry: uv tool run nox -s typecheck --no-install
        language: system
        pass_filenames: false
        require_serial: true

      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
        args: ["-q", "--tb=short", "--strict-markers", "--disable-warnings"]
