# .github/workflows/guard-main-origin.yml
name: Guard-Main-Origin

on:
  pull_request:
    branches: [main]            # PRs whose *target* is main only

jobs:
  ensure-valid-origin:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from allowed branch
        run: |
          BRANCH="${{ github.head_ref }}"

          # Allow PRs from dev or hotfix branches
          if [[ "$BRANCH" == "dev" ]] || [[ "$BRANCH" =~ ^hotfix-.* ]]; then
            echo "✅ Origin branch '$BRANCH' is allowed"
          else
            echo "::error::Main only accepts PRs from 'dev' or 'hotfix-*' branches. Current branch: $BRANCH"
            exit 1
          fi
