# .github/workflows/test-release.yml
name: Test Release

on:
  push:
    tags:
      - 'v*-alpha.*'
      - 'v*-beta.*'
      - 'v*-rc.*'

jobs:
  test-release:
    name: Create Test Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5.3.0

        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Configure TestPyPI repository
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_TOKEN }}

      - name: Build package
        run: poetry build

      - name: Publish to TestPyPI
        run: poetry publish -r testpypi
